apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-flag-service
    {{- include "togglemaster.labels" .| nindent 4 }}
  name: app-flag-service
  namespace: {{ (index .Values "flag-service").namespace }}
spec:
  strategy:
    type: Recreate
  replicas: {{ (index .Values "flag-service").replicas}}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app-flag-service
  template:
    metadata:
      labels:
        app: app-flag-service
    spec:
      containers:
        - name: app-flag-service
          image: {{ (index .Values "flag-service").image }}
          imagePullPolicy: {{ (index .Values "flag-service").imagePullPolicy }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          startupProbe:
           httpGet:
             path: /health
             port: {{ (index .Values "flag-service").port }}
           failureThreshold: 180
           periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: {{ (index .Values "flag-service").port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ (index .Values "flag-service").port }}
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          envFrom:
            {{- toYaml (index .Values "flag-service").envFrom | nindent 12 }}
